#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         3
bspc config window_gap          12
bspc config border_radius	10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#b7bdf8"
bspc config active_border_color "#b7bdf8"
bspc config focused_border_color "#b7bdf8"
bspc config presel-feedback_colour "#fc9d63"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true
bspc config down_padding 10




nitrogen --restore &
xrandr --output HDMI-1 --mode 1920x1080 &
xinput --set-prop 12 295 -1,9
polybar &
setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle"
xsetroot -cursor_name left_ptr &
